### ISSUE TITLE
Data only displayed for one string

### ISSUE THREAD

**Issue by Dividing6043** [jpcornil-git/HA-sma#4]
Firstly, many thanks for this integration.

I have noticed that the integration only seems to show data for the first string. My inverter (SB 4000TL) has two strings of PV attached.
Would it be possible for this integration to be updated to show the data from both strings?

![image](https://user-images.githubusercontent.com/114674260/234828787-70213d0e-5936-4c47-a645-96893910d078.png)

![image](https://user-images.githubusercontent.com/114674260/234828954-1767edc5-31a1-4162-b009-ed7791e69d91.png)

**Comment by jpcornil-git** [comment]
Could you add the following to your configuration.yaml, restart HA and report logs ?
``` yaml
logger:
  default: warning
  logs:
    custom_components.sma_webbox: debug
```
